apiVersion: v1
kind: Service
metadata:
  name: svc-motroni-api
spec:
  type: NodePort
  ports:
    - port: 80 # encaminha 31100 > encaminha 3000
      nodePort: 31100
      targetPort: 3000
  selector:
    app: motroni-api
