apiVersion: v1
kind: Pod
metadata:
  name: front-pod
  labels:
    app: front-pod
spec:
  containers:
    - name: front-pod
      image: gabriesmotroni/project-angular-env:v1
      ports:
        - containerPort: 80 # Porta do nginx
      env:
        - name: URL_IMAGEM
          valueFrom:
            secretKeyRef:
              name: opaque-secret
              key: URL_IMAGEM
